# Form implementation generated from reading ui file 'Jlab/Core/KanjiTrainer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KanjiTrainerUi(object):
    def setupUi(self, KanjiTrainerUi):
        KanjiTrainerUi.setObjectName("KanjiTrainerUi")
        KanjiTrainerUi.resize(223, 189)
        self.verticalLayout = QtWidgets.QVBoxLayout(KanjiTrainerUi)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=KanjiTrainerUi)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.heisigSpinBox = QtWidgets.QSpinBox(parent=self.groupBox)
        self.heisigSpinBox.setObjectName("heisigSpinBox")
        self.gridLayout.addWidget(self.heisigSpinBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=KanjiTrainerUi)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.furiganaWithSpaceRadioButton = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.furiganaWithSpaceRadioButton.setChecked(True)
        self.furiganaWithSpaceRadioButton.setObjectName("furiganaWithSpaceRadioButton")
        self.verticalLayout_2.addWidget(self.furiganaWithSpaceRadioButton)
        self.furiganaWithoutSpaceRadioButton = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.furiganaWithoutSpaceRadioButton.setObjectName("furiganaWithoutSpaceRadioButton")
        self.verticalLayout_2.addWidget(self.furiganaWithoutSpaceRadioButton)
        self.jlabRadioButton = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.jlabRadioButton.setObjectName("jlabRadioButton")
        self.verticalLayout_2.addWidget(self.jlabRadioButton)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(KanjiTrainerUi)
        QtCore.QMetaObject.connectSlotsByName(KanjiTrainerUi)

    def retranslateUi(self, KanjiTrainerUi):
        _translate = QtCore.QCoreApplication.translate
        KanjiTrainerUi.setWindowTitle(_translate("KanjiTrainerUi", "Kanji Trainer"))
        self.groupBox.setTitle(_translate("KanjiTrainerUi", "Specify learned kanji"))
        self.label.setText(_translate("KanjiTrainerUi", "RTK/Heisig index:"))
        self.groupBox_2.setTitle(_translate("KanjiTrainerUi", "Display settings"))
        self.furiganaWithSpaceRadioButton.setText(_translate("KanjiTrainerUi", "Furigana with spaces"))
        self.furiganaWithoutSpaceRadioButton.setText(_translate("KanjiTrainerUi", "Furigana without spaces"))
        self.jlabRadioButton.setText(_translate("KanjiTrainerUi", "Jlab"))
